### ISSUE TITLE
Not able to run app on Kali 2019.01

### ISSUE THREAD

**Issue by sumgro** [LukaSikic/subzy#1]
Hi!

Thank you for the great tool.

I've it installed on my Kali VM running 2019.01 and have not been successful using the tool in the last 2 days. Followed the instruction to clone the git repository and when issuing the command ./subzy or sudo bash subzy, getting the below error messages:

subzy  ‹master› 
╰─➤  ./subzy
zsh: exec format error: ./subzy
---------------
subzy  ‹master› 
╰─➤  sudo bash subzy                                                                                                               
subzy: subzy: cannot execute binary file

Kindly suggest the way to rectify the same.

Thanks

**Comment by LukaSikic** [comment]
You will need to compile it from the source in that case. Install golang and then run `go build subzy.go` and it will create new binary file `subzy` which you can run

**Comment by sumgro** [comment]
Thank you for the quick revert. The solution worked. Request of the update of the Readme information for the same.

Confirmation:

/subzy  ‹master*› 
╰─➤  ./subzy                                                                                                                  
Usage: ./subzy [OPTIONS] argument ...
  -concurrency int
    	Number of concurrent checks (default 10)
  -hide_fails
    	Don't display failed results
  -https
    	Force https protocol if not no protocol defined for target (default false)
  -target string
    	Single or multiple subdomains separated by comma
  -targets string
    	File path to list of subdomains to be scanned
  -timeout int
    	Request timeout in seconds (default 10)
  -verify_ssl
    	If set to true it won't check sites with insecure SSL and return HTTP Error

**Comment by sumgro** [comment]
Thank you updating the Readme.

**Comment by sebastgav2014** [comment]
Hi, LukaSikic.

I'm having a problem installing on kali 2024.
