### ISSUE TITLE
Can install - unexpected directory layout

### ISSUE THREAD

**Issue by shabbadont** [LukaSikic/subzy#11]
GOROOT and GOPATH are correct. Not sure what is causing this/
I'm using Kali for this.

unexpected directory layout:
	import path: _/root/go/src/github.com/lukasikic/subzy/src
	root: /root/go/src
	dir: /root/go/src/github.com/lukasikic/subzy/src
	expand root: /root/go
	expand dir: /root/go/src/github.com/lukasikic/subzy/src
	separator: /

**Comment by xoffense** [comment]
same issue for me also

**Comment by elzozz** [comment]
Ran into the same issue... newer versions of golang no longer accepts absolute path imports. So change the import path as follows:
`import (
        "github.com/lukasikic/subzy/src"
        "flag"
        "fmt"
        "os"
)
`
