### ISSUE TITLE
Error processing: Process: Fingerprints: unexpected end of JSON input

### ISSUE THREAD

**Issue by h3cksamrat** [LukaSikic/subzy#15]
When I give the following command, I get an error.
```bash
$ subzy -targets findomain_subd.txt
2021/05/05 05:17:56 Error processing: Process: Fingerprints: unexpected end of JSON input
```

**Comment by lateralusd** [comment]
Would you mind showing us the output of fingerprints.json from your home directory.

**Comment by rahuldora377** [comment]
Deleting fingerprints.json from home directory fixed my issue

**Comment by lateralusd** [comment]
@rahuldora377 perhaps it was malformed. When the `subzy` run it will check whether fingerprints.json exists in the home directory and will load fingerprints from there. If it is not present, it will be downloaded from this repo.

**Comment by lateralusd** [comment]
And according to the error, it indeed looks like it was malformed

**Comment by rahuldora377** [comment]
@lateralusd yeah i also think so but i haven't done anything to that json file but there might be chances that json file being changed by other program in my system

**Comment by manoprasanth-m** [comment]
I have deleted the fingerprints.json file but I still encounter the problem.

**Comment by lateralusd** [comment]
Is it the same error?
