### ISSUE TITLE
not able to install subzy

### ISSUE THREAD

**Issue by kaal-kali** [LukaSikic/subzy#21]
go install -v github.com/lukasikic/subzy
go install: version is required when current directory is not in a module
	Try 'go install github.com/lukasikic/subzy@latest' to install the latest version

**Comment by mufazmi** [comment]
Ummm..! I am also not able to install it..

![image](https://user-images.githubusercontent.com/34832943/157118941-ed90e064-58fa-4f6e-9180-212eb2c13796.png)

**Comment by mani0218** [comment]
i too facing the same issue how to resolve it ..?

**Comment by axosecurity** [comment]
sudo go install -v github.com/lukasikic/subzy
[sudo] password for axosolaman: 
go: 'go install' requires a version when current directory is not in a module
	Try 'go install github.com/lukasikic/subzy@latest' to install the latest version
                                                                                                                                                                                                                                              
┌──(axosolaman㉿kali)-[~/tool/subzy]
└─$ go install github.com/lukasikic/subzy@latest                                                                                                                                                                                          1 ⨯
go: finding module for package github.com/mitchellh/go-homedir
go: finding module for package github.com/logrusorgru/aurora
go: found github.com/logrusorgru/aurora in github.com/logrusorgru/aurora v2.0.3+incompatible
go: found github.com/mitchellh/go-homedir in github.com/mitchellh/go-homedir v1.1.0

**Comment by akas4h** [comment]
i am also facing this issuss

**Comment by pacho15** [comment]
it issue is bcoz **go get** is not working in new version you have to use command `go install github.com/lukasikic/subzy@latest`
