### ISSUE TITLE
To not installing 

### ISSUE THREAD

**Issue by Shankar9393** [LukaSikic/subzy#28]
┌──(kali㉿kali)-[~]
└─$ sudo go install -v github.com/lukasikic/subzy@latest
go: finding module for package github.com/mitchellh/go-homedir
go: finding module for package github.com/logrusorgru/aurora
go: found github.com/logrusorgru/aurora in github.com/logrusorgru/aurora v2.0.3+incompatible
go: found github.com/mitchellh/go-homedir in github.com/mitchellh/go-homedir v1.1.0

**Comment by ahadalichowdhury** [comment]
I am also facing this kind of problem , How i solve this?? anyone help me

**Comment by magrisya** [comment]
try :
`sudo go install -v github.com/lukasikic/subzy@latest`
`PATH=/root/go/bin:$PATH`
`subzy -h`

**Comment by websecnl** [comment]
> try : `sudo go install -v github.com/lukasikic/subzy@latest` `PATH=/root/go/bin:$PATH` `subzy -h`

This worked, thank you!

**Comment by md5tack** [comment]
> try : `sudo go install -v github.com/lukasikic/subzy@latest` `PATH=/root/go/bin:$PATH` `subzy -h`

i have not "/home/user/go/*bin* " i have /go/pkg 
how to i install current version
