### ISSUE TITLE
error after runnig tool - Error: Process: Fingerprints: invalid character ':' after top-level value

### ISSUE THREAD

**Issue by sushantdhopat** [LukaSikic/subzy#31]
getting error after running the tool with the bellow command

```subzy r --target test.google.com```

Error: Process: Fingerprints: invalid character ':' after top-level value

**Comment by p0intsec** [comment]
Hi, 

me too, the same error:
Error: Process: Fingerprints: invalid character ':' after top-level value

**Comment by lateralusd** [comment]
Until the PR gets merged, please download [https://raw.githubusercontent.com/LukaSikic/subzy/master/runner/fingerprints.json](https://raw.githubusercontent.com/LukaSikic/subzy/master/runner/fingerprints.json) and save it inside the `~/subzy/` directory.
