### ISSUE TITLE
Fingerprint for Gemfury is overly broad

### ISSUE THREAD

**Issue by MegaManSec** [LukaSikic/subzy#37]
Hey there,

First off: thank you for this great tool.

It seems that the fingerprint for Gemfury is overly broad, and can likely be improved. https://github.com/LukaSikic/subzy/blob/master/runner/fingerprints.json#L285 "404: This page could not be found." applies to many 'normal' websites which are completely unrelated to Gemfury.

Is it possible to multiple fingerprints that must match on a page? "404: This page could not be found." and "RubyGems", perhaps?

Cheers

**Comment by NSEcho** [comment]
Hi, right now it matches the first occurrence of the match. If you are familiar more with Gemfury, please feel free to do PR with more specific fingerprint.

**Comment by MegaManSec** [comment]
Fixes by #38.
