### ISSUE TITLE
how install Subzy in Windows 10 

### ISSUE THREAD

**Issue by ErrorMySQL** [LukaSikic/subzy#43]
how install Subzy in Windows 10 ?

**Comment by PishangShedappp** [comment]
- You can download golang for windows here first https://go.dev/doc/install 

- After done installing you can run ‘ go install -v github.com/LukaSikic/subzy@latest’ in cmd/powershell

**Comment by LukaSikic** [comment]
Thank you @PishangShedappp .

@ErrorMySQL if you face any issues, feel free to reopen the issue.
