### ISSUE TITLE
Cleaner output

### ISSUE THREAD

**Issue by mjdubell** [LukaSikic/subzy#5]
I think it would be great if we could specify an option that returns the output without colors and extra information. For example:

```
VULNERABLE|subdomain.domain.com
NOT VULNERABLE|subdomain1.domain.com
```

An option that only outputs vulnerable subdomains would be nice as well.

**Comment by LukaSikic** [comment]
Feel free to submit a pull request

**Comment by ZhenwarX** [comment]
When it will be possible?
