### ISSUE TITLE
Cant run any comand.

### ISSUE THREAD

**Issue by fernstedt** [LukaSikic/subzy#60]
subzy --targets subs.txt
Error: unknown flag: --targets
Usage:
  subzy [command]

Available Commands:
  help        Help about any command
  run         Run subzy
  version     Print subzy version

Flags:
  -h, --help   help for subzy

Use "subzy [command] --help" for more information about a command.

-h --help does not work either.
go version go1.23.1 linux/amd64

**Comment by NSEcho** [comment]
`subzy run`. Please read `README.md` file.
