### ISSUE TITLE
Unable to run the tool 

### ISSUE THREAD

**Issue by akhiljain029** [LukaSikic/subzy#7]
/subzy -target=list.txt -https
[ * ] Loaded 1 targets
[ Yes ] HTTPS by default (--https)
[ 10 ] Concurrent requests (--concurrency)
[ No ] Check target only if SSL is valid (--verify_ssl)
[ 10 ] HTTP request timeout (in seconds) (--timeout)
[ No ] Show only potentially vulnerable subdomains (--hide_fails)
🔥 Good luck 🔥 
[  HTTP ERROR  ]  -  list.txt

how to fix this.

**Comment by LukaSikic** [comment]
If you are loading list of targets, specify it with `targets` flag. Ex. ./subzy -targets list.txt -https

**Comment by ArunVR2112** [comment]
subzy -target subs_n.txt -https
[ * ] Loaded 1 targets
[ * ] Loaded 44 fingerprints
[ Yes ] HTTPS by default (--https)
[ 10 ] Concurrent requests (--concurrency)
[ No ] Check target only if SSL is valid (--verify_ssl)
[ 10 ] HTTP request timeout (in seconds) (--timeout)
[ No ] Show only potentially vulnerable subdomains (--hide_fails)
[  HTTP ERROR  ]  -  subs_n.txt

**Comment by ArunVR2112** [comment]
subzy -target subs_n.txt -https
[ * ] Loaded 1 targets
[ * ] Loaded 44 fingerprints
[ Yes ] HTTPS by default (--https)
[ 10 ] Concurrent requests (--concurrency)
[ No ] Check target only if SSL is valid (--verify_ssl)
[ 10 ] HTTP request timeout (in seconds) (--timeout)
[ No ] Show only potentially vulnerable subdomains (--hide_fails)
[ HTTP ERROR ] - subs_n.txt

how to fix this:

**Comment by LukaSikic** [comment]
Read my previous comment on this issue. When loading target hosts from a wordlist, you must use `-targets` flag

**Comment by Moshi-07** [comment]
/subzy -targets=home/mine/Desktop/Test.txt -https
[ * ] Loaded 1 targets
[ Yes ] HTTPS by default (--https)
[ 10 ] Concurrent requests (--concurrency)
[ No ] Check target only if SSL is valid (--verify_ssl)
[ 10 ] HTTP request timeout (in seconds) (--timeout)
[ No ] Show only potentially vulnerable subdomains (--hide_fails)
🔥 Good luck 🔥
[ HTTP ERROR ] - list.txt

how to fix this.

**Comment by Vibhpr-gaalib** [comment]
> 

its 

subzy --targets=targetsList.txt  

use targets instead of target.

**Comment by Moshi-07** [comment]
Got it Bro Thanks.

**Comment by NSEcho** [comment]
Well, that is expected behaviour. Try pinging `test.google.com` and you should receive `ping: cannot resolve test.google.com: Unknown host` that is because there are no any DNS records for that subdomain.

**Comment by Lord-Ravan** [comment]
well with linktr.ee also I am getting the same

**Comment by Lord-Ravan** [comment]
ohk

**Comment by alanwez** [comment]
i got error, ERROR: EOF ?
