### ISSUE TITLE
cannot find package "github.com/lukasikic/subzy" 

### ISSUE THREAD

**Issue by AsifIqbal093** [LukaSikic/subzy#9]
here is the details oof the error....

sudo go install -v github.com/lukasikic/subzy
cannot find package "github.com/lukasikic/subzy" in any of:
	/usr/lib/go-1.15/src/github.com/lukasikic/subzy (from $GOROOT)
	/root/go/src/github.com/lukasikic/subzy (from $GOPATH)

**Comment by ravkishu** [comment]
Hi @AsifIqbal093, make sure you have got these already setups:
1. `$GOROOT` and `$GOPATH` setup correctly.
2. Verify by typing in terminal `which go` or `go version`
3. It should return something like this
```zsh
➜  which go
/usr/local/go/bin//go

➜  go version
go version go1.15.5 linux/amd64

➜  echo $GOROOT
/usr/local/go

➜  echo $GOPATH
/root/go
```

Once you get the output similar to above you can install *subzy* by typing in terminal below command:
```zsh
GO111MODULE=on go get -u -v github.com/lukasikic/subzy
```

This will definitely solve you're issue, if you've setup go-lang correctly
